package kamai.app.models

data class AdData(
    var inApp: Boolean = false,
    var CappingCounter: Int = 1,
    var nativeRequests: Int = 10,
    var bannerRequests: Int = 10,
    var interstitialRequests: Int = 0,
    var nativeIdHCPM1: String = "",
    var nativeIdHCPM2: String = "",
    var nativeIdMCPM1: String = "",
    var nativeIdMCPM2: String = "",
    var nativeIdLCPM: String = "",
    var BannerId1: String = "",
    var BannerId2: String = "",
    var BannerId3: String = "",
    var BannerId4: String = "",
    var BannerId5: String = "",
    var InterstitialIdHCPM1: String = "",
    var InterstitialIdHCPM2: String = "",
    var InterstitialIdMCPM1: String = "",
    var InterstitialIdMCPM2: String = "",
    var InterstitialIdLCPM: String = "",
    var AppOpenAdId: String = "",
    var layoutTemplate: String = "bcta",
    var ApplovinCtaColor: String = "#000000",
    var ApplovinCtaTextColor: String = "#ffffff",
    var AdmobCtaColor: String = "#000000",
    var AdmobCtaTextColor: String = "#ffffff",
    var applovinNativeId: String = "",
    var isOn: String = "on",
    var nativeScale: String = "center",
    var reportClassName: String = "off",
    var classesJson: String = "",
    var noAdsButton: String = "off",
    var appUpdateType: String = "1",
    var loadingDuration : String = "1500",
    var  SplashNativeAd:String = "off",
    var SplashInterstitialAd:String = "off",
)